route:
  group_by: ['example']
  group_interval: 10s
  repeat_interval: 10s
  receiver: "webhook-receiver-up"

  routes:
    - match:
        action: upQueue
      receiver: "webhook-receiver-up"
    - match:
        action: downQueue
      receiver: "webhook-receiver-down"

receivers:
  - name: "webhook-receiver-up"
    webhook_configs:
      - url:
        send_resolved: true
  - name: "webhook-receiver-down"
    webhook_configs:
    - url:
      send_resolved: true


