groups:
  - name: example
    rules:
      - alert: HighErrorRate
        expr: rabbitmq_queue_messages_ready{durable="true",policy="",queue="messages",vhost="/"} == 8
        labels:
          severity: critical
          action: upQueue
        annotations:
          summary: Escala 1 quando o tamanho da fila chegar a 5
      - alert: LowErrorRate
        expr: rabbitmq_queue_messages_ready{durable="true",policy="",queue="messages",vhost="/"} == 0
        labels:
          severity: critical
          action: downQueue
        annotations:
          summary: Deixar apenas uma aplicação quando o tamanho da fila chegar a 0